#!/bin/bash
#
# CryoProcess - Control Script
# Author: Karunakar Pothula
#
# Usage:
#   ./cryoprocess.sh install           - Full setup (installs everything with sudo)
#   ./cryoprocess.sh install --user    - Non-root setup (downloads binaries locally)
#   ./cryoprocess.sh install --conda   - Conda setup (installs into conda env)
#   ./cryoprocess.sh start             - Start services
#   ./cryoprocess.sh stop              - Stop services
#   ./cryoprocess.sh restart           - Restart services
#   ./cryoprocess.sh status            - Check status
#   ./cryoprocess.sh logs              - View logs
#

set -e

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Directories
BACKEND_DIR="$SCRIPT_DIR/backend"
FRONTEND_DIR="$SCRIPT_DIR/frontend"
PID_DIR="$SCRIPT_DIR/pids"
LOG_DIR="$SCRIPT_DIR/logs"
DEPS_DIR="$SCRIPT_DIR/deps"

# Create directories
mkdir -p "$PID_DIR" "$LOG_DIR"

# Files
PID_FILE="$PID_DIR/nodejs.pid"
LOG_FILE="$LOG_DIR/nodejs.log"

# Default port
PORT=${PORT:-8001}

# Use local deps if they exist (installed by --user mode)
if [ -d "$DEPS_DIR/node/bin" ]; then
    export PATH="$DEPS_DIR/node/bin:$PATH"
fi
if [ -d "$DEPS_DIR/mongodb/bin" ]; then
    export PATH="$DEPS_DIR/mongodb/bin:$PATH"
fi

# Activate conda env if installed via --conda mode
CONDA_ENV_FILE="$SCRIPT_DIR/.conda_env"
if [ -f "$CONDA_ENV_FILE" ]; then
    CRYO_CONDA_ENV=$(cat "$CONDA_ENV_FILE")
    if command -v conda &>/dev/null; then
        eval "$(conda shell.bash hook 2>/dev/null)"
        conda activate "$CRYO_CONDA_ENV" 2>/dev/null || true
    fi
fi

# ============================================================
# Helper Functions
# ============================================================

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${BLUE}==>${NC} $1"
}

check_command() {
    if command -v "$1" &> /dev/null; then
        return 0
    fi
    return 1
}

# ============================================================
# Write .env file
# ============================================================

# Reads optional OLD_* variables as defaults (set by do_reconfigure)
write_env_file() {
    ENV_FILE="$SCRIPT_DIR/.env"

    log_step "Writing .env configuration file..."
    echo ""

    # Verify node is available (needed for JWT secret generation)
    if ! check_command node; then
        log_error "Node.js not found in PATH. Cannot generate .env file."
        log_error "This should not happen — please report this bug."
        exit 1
    fi

    # Generate JWT secret (reuse old one if available)
    if [ -n "$OLD_JWT_SECRET" ]; then
        JWT_SECRET="$OLD_JWT_SECRET"
        log_info "Reusing existing JWT secret"
    else
        JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
        log_info "Generated new JWT secret"
    fi

    # Prompt for required paths (show old values as defaults)
    echo ""
    log_step "Configure required paths:"
    echo ""

    local default_data="${OLD_ROOT_PATH:-/path/to/your/data}"
    read -p "  Data root path [$default_data]: " DATA_PATH
    DATA_PATH="${DATA_PATH:-$default_data}"

    local default_relion="${OLD_RELION_PATH:-}"
    if [ -n "$default_relion" ]; then
        read -p "  RELION container path [$default_relion]: " RELION_PATH
        RELION_PATH="${RELION_PATH:-$default_relion}"
    else
        read -p "  RELION container path (.sif file, or leave empty): " RELION_PATH
    fi

    # Build SINGULARITY_BIND_PATHS from the paths entered
    BIND_PATHS=""
    if [ -n "$DATA_PATH" ] && [ "$DATA_PATH" != "/path/to/your/data" ]; then
        BIND_PATHS="$DATA_PATH:$DATA_PATH"
    fi
    if [ -n "$RELION_PATH" ]; then
        RELION_DIR=$(dirname "$RELION_PATH")
        if [ -n "$BIND_PATHS" ]; then
            if [ "$RELION_DIR" != "$DATA_PATH" ]; then
                BIND_PATHS="$BIND_PATHS,$RELION_DIR:$RELION_DIR"
            fi
        else
            BIND_PATHS="$RELION_DIR:$RELION_DIR"
        fi
    fi

    # Write .env file
    cat > "$ENV_FILE" << ENVEOF
# =============================================================================
# CryoProcess - Configuration
# =============================================================================
# Generated by: ./cryoprocess.sh install
#
# Default Admin Login:
#   Email:    admin@example.com
#   Password: admin123
# =============================================================================

# =============================================================================
# 1. SERVER
# =============================================================================

PORT=${OLD_PORT:-8001}
NODE_ENV=${OLD_NODE_ENV:-production}
CORS_ORIGIN=${OLD_CORS_ORIGIN:-*}
LOG_LEVEL=${OLD_LOG_LEVEL:-info}

# =============================================================================
# 2. DATABASE
# =============================================================================

MONGODB_URI=${OLD_MONGODB_URI:-mongodb://localhost:27017/cryoprocess-db}

# =============================================================================
# 3. AUTHENTICATION
# =============================================================================

JWT_SECRET=$JWT_SECRET
JWT_EXPIRES_IN=${OLD_JWT_EXPIRES_IN:-7d}

# =============================================================================
# 4. DATA PATH (Required — edit for your system)
# =============================================================================

ROOT_PATH=$DATA_PATH

# Archive / cold storage path (optional)
# Move completed projects to cheaper storage (e.g., S3 mounted via blobfuse).
# Leave unset or empty to disable archive/restore features.
# ARCHIVE_PATH=${OLD_ARCHIVE_PATH:-/mnt/archive/projects}

# =============================================================================
# 5. SLURM CLUSTER
# =============================================================================

SLURM_PARTITION=${OLD_SLURM_PARTITION:-batch}
SLURM_SUBMIT_COMMAND=${OLD_SLURM_SUBMIT_COMMAND:-sbatch}
SLURM_POLL_INTERVAL=${OLD_SLURM_POLL_INTERVAL:-3000}

# =============================================================================
# 6. SSH REMOTE CLUSTER (Optional)
# Enable if CryoProcess runs on a different machine than the SLURM cluster.
# Requires a shared filesystem (NFS/Lustre) for ROOT_PATH.
# =============================================================================

# SLURM_USE_SSH=false
# SLURM_SSH_HOST=cluster.example.com
# SLURM_SSH_USER=myuser
# SLURM_SSH_PORT=22
# SLURM_SSH_KEY_PATH=~/.ssh/id_rsa

# =============================================================================
# 7. SOFTWARE & CONTAINER
# =============================================================================

RELION_PATH=${RELION_PATH:-}
SINGULARITY_BIND_PATHS=${BIND_PATHS:-}
SINGULARITY_OPTIONS=${OLD_SINGULARITY_OPTIONS:---nv}

# CTF estimation
CTFFIND_EXE=${OLD_CTFFIND_EXE:-}
GCTF_EXE=${OLD_GCTF_EXE:-}

# Motion correction
MOTIONCOR2_EXE=${OLD_MOTIONCOR2_EXE:-}

# Model building
MODELANGELO_EXE=${OLD_MODELANGELO_EXE:-}

# =============================================================================
# 8. EMAIL NOTIFICATIONS (Optional)
# Send email when a job completes or fails. Users toggle per-job via the
# bell icon in Job Actions. Requires an SMTP server.
# =============================================================================

# EMAIL_NOTIFICATIONS_ENABLED=false
# SMTP_HOST=smtp.youruni.edu
# SMTP_PORT=587
# SMTP_SECURE=false
# SMTP_USER=your-email@youruni.edu
# SMTP_PASS=your-password
# SMTP_FROM=CryoProcess <your-email@youruni.edu>

# =============================================================================
# 9. SMARTSCOPE INTEGRATION (Optional)
# Machine-to-machine auth for SmartScope microscope automation.
# SmartScope sends X-API-Key header; CryoProcess validates against this key.
# Requires a "smartscope" user account (create via Admin > Users after install).
# =============================================================================

# Shared API key (must match SmartScope's config)
# Generate: node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
# SMARTSCOPE_API_KEY=
ENVEOF

    echo ""
    log_info "Configuration saved to .env"
}

# ============================================================
# Detect Linux Distribution
# ============================================================

detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS_NAME=$NAME
        OS_ID=$ID
        OS_VERSION=$VERSION_ID
    elif [ -f /etc/redhat-release ]; then
        OS_NAME="Red Hat"
        OS_ID="rhel"
    elif [ -f /etc/debian_version ]; then
        OS_NAME="Debian"
        OS_ID="debian"
    else
        OS_NAME="Unknown"
        OS_ID="unknown"
    fi

    echo -e "${CYAN}"
    echo "=============================================="
    echo "  CryoProcess - System Detection"
    echo "=============================================="
    echo -e "${NC}"
    echo "  OS:       $OS_NAME"
    echo "  Version:  $OS_VERSION"
    echo "  Arch:     $(uname -m)"
    echo "  Kernel:   $(uname -r)"
    echo ""
}

# ============================================================
# Install User-Local Dependencies (no sudo — downloads binaries)
# ============================================================

_install_user_deps() {
    echo -e "${CYAN}"
    echo "=============================================="
    echo "  Downloading Dependencies (user-local)"
    echo "=============================================="
    echo -e "${NC}"

    mkdir -p "$DEPS_DIR"

    local ARCH
    ARCH=$(uname -m)
    case "$ARCH" in
        x86_64)  ARCH="x64" ;;
        aarch64) ARCH="arm64" ;;
        *)
            log_error "Unsupported architecture: $ARCH"
            exit 1
            ;;
    esac

    # --- Node.js ---
    if ! check_command node; then
        local NODE_VERSION="v20.18.1"
        local NODE_DIR="node-${NODE_VERSION}-linux-${ARCH}"
        local NODE_URL="https://nodejs.org/dist/${NODE_VERSION}/${NODE_DIR}.tar.xz"

        log_step "Downloading Node.js ${NODE_VERSION} (linux-${ARCH})..."
        curl -fsSL "$NODE_URL" -o "$DEPS_DIR/node.tar.xz"

        log_step "Extracting..."
        tar -xJf "$DEPS_DIR/node.tar.xz" -C "$DEPS_DIR"
        rm -rf "$DEPS_DIR/node"
        mv "$DEPS_DIR/$NODE_DIR" "$DEPS_DIR/node"
        rm -f "$DEPS_DIR/node.tar.xz"

        export PATH="$DEPS_DIR/node/bin:$PATH"
        log_info "Node.js installed to deps/node/ — $(node --version)"
    else
        log_info "Node.js already available: $(node --version)"
    fi

    # --- MongoDB ---
    if ! check_command mongod && ! check_command mongosh; then
        # Detect distro for download URL
        local MONGO_VERSION="8.0.4"
        local MONGO_PLATFORM=""
        if [ -f /etc/os-release ]; then
            . /etc/os-release
            case "$ID" in
                ubuntu)
                    case "$VERSION_ID" in
                        24.04) MONGO_PLATFORM="ubuntu2404" ;;
                        22.04) MONGO_PLATFORM="ubuntu2204" ;;
                        20.04) MONGO_PLATFORM="ubuntu2004" ;;
                        *)     MONGO_PLATFORM="ubuntu2204" ;;
                    esac
                    ;;
                debian)
                    case "$VERSION_ID" in
                        12) MONGO_PLATFORM="debian12" ;;
                        11) MONGO_PLATFORM="debian11" ;;
                        *)  MONGO_PLATFORM="debian12" ;;
                    esac
                    ;;
                rhel|centos|rocky|almalinux)
                    MONGO_PLATFORM="rhel80"
                    ;;
                *)
                    MONGO_PLATFORM="ubuntu2204"
                    ;;
            esac
        else
            MONGO_PLATFORM="ubuntu2204"
        fi

        local MONGO_ARCH
        case "$ARCH" in
            x64)   MONGO_ARCH="x86_64" ;;
            arm64) MONGO_ARCH="aarch64" ;;
        esac

        local MONGO_DIR="mongodb-linux-${MONGO_ARCH}-${MONGO_PLATFORM}-${MONGO_VERSION}"
        local MONGO_URL="https://fastdl.mongodb.org/linux/${MONGO_DIR}.tgz"

        log_step "Downloading MongoDB ${MONGO_VERSION} (${MONGO_PLATFORM}, ${MONGO_ARCH})..."
        curl -fsSL "$MONGO_URL" -o "$DEPS_DIR/mongodb.tgz"

        log_step "Extracting..."
        tar -xzf "$DEPS_DIR/mongodb.tgz" -C "$DEPS_DIR"
        rm -rf "$DEPS_DIR/mongodb"
        mv "$DEPS_DIR/$MONGO_DIR" "$DEPS_DIR/mongodb"
        rm -f "$DEPS_DIR/mongodb.tgz"

        export PATH="$DEPS_DIR/mongodb/bin:$PATH"
        log_info "MongoDB installed to deps/mongodb/"

        # Create local data directory and start mongod
        local MONGO_DATA="$DEPS_DIR/mongodb/data"
        local MONGO_LOG="$DEPS_DIR/mongodb/mongod.log"
        mkdir -p "$MONGO_DATA"

        log_step "Starting local MongoDB..."
        if "$DEPS_DIR/mongodb/bin/mongod" \
            --dbpath "$MONGO_DATA" \
            --logpath "$MONGO_LOG" \
            --port 27017 \
            --fork; then
            log_info "MongoDB running (data: deps/mongodb/data/)"
        else
            log_warn "Could not start MongoDB. Check: $MONGO_LOG"
            log_info "You can set MONGODB_URI in .env to use a remote MongoDB instead."
        fi
    else
        log_info "MongoDB already available"
    fi

    echo ""
    echo -e "${GREEN}Local dependencies installed in deps/${NC}"
    echo ""
}

# ============================================================
# Install Conda Dependencies (no sudo — uses conda/mamba)
# ============================================================

_install_conda_deps() {
    echo -e "${CYAN}"
    echo "=============================================="
    echo "  Installing Dependencies (conda)"
    echo "=============================================="
    echo -e "${NC}"

    # Check conda is available
    if ! check_command conda && ! check_command mamba; then
        log_error "conda/mamba not found!"
        echo ""
        echo "  Install Miniconda first:"
        echo "    https://docs.conda.io/en/latest/miniconda.html"
        echo ""
        echo "  Or Mambaforge:"
        echo "    https://github.com/conda-forge/miniforge"
        echo ""
        exit 1
    fi

    # Prefer mamba over conda (faster solver)
    local CONDA_CMD="conda"
    if check_command mamba; then
        CONDA_CMD="mamba"
        log_info "Using mamba (faster solver)"
    fi

    local ENV_NAME="cryoprocess"

    # Initialize conda for this shell
    eval "$(conda shell.bash hook 2>/dev/null)"

    # Create env if it doesn't exist
    if conda env list 2>/dev/null | grep -q "^${ENV_NAME} "; then
        log_info "Conda environment '$ENV_NAME' already exists"
    else
        log_step "Creating conda environment: $ENV_NAME..."
        $CONDA_CMD create -n "$ENV_NAME" nodejs=20 mongodb=8.0 -c conda-forge -y
    fi

    # Activate
    conda activate "$ENV_NAME"

    # Store env name so future commands auto-activate
    echo "$ENV_NAME" > "$SCRIPT_DIR/.conda_env"

    log_info "Node.js: $(node --version)"
    log_info "MongoDB: installed via conda"

    # Create local data directory for mongod
    local MONGO_DATA="$DEPS_DIR/mongodb/data"
    local MONGO_LOG="$DEPS_DIR/mongodb/mongod.log"
    mkdir -p "$MONGO_DATA"

    log_step "Starting local MongoDB..."
    if mongod \
        --dbpath "$MONGO_DATA" \
        --logpath "$MONGO_LOG" \
        --port 27017 \
        --fork; then
        log_info "MongoDB running (data: deps/mongodb/data/)"
    else
        log_warn "Could not start MongoDB. Check: $MONGO_LOG"
        log_info "You can set MONGODB_URI in .env to use a remote MongoDB instead."
    fi

    echo ""
    echo -e "${GREEN}Conda dependencies ready (env: $ENV_NAME)${NC}"
    echo ""
}

# ============================================================
# Install System Dependencies (internal helper — requires sudo)
# ============================================================

_install_system_deps() {
    detect_os

    echo -e "${CYAN}"
    echo "=============================================="
    echo "  Installing System Dependencies"
    echo "=============================================="
    echo -e "${NC}"

    # Check if running as root or with sudo
    if [ "$EUID" -ne 0 ]; then
        SUDO="sudo"
        log_info "Will use sudo for package installation"
    else
        SUDO=""
    fi

    case "$OS_ID" in
        ubuntu|debian|linuxmint|pop)
            log_step "Detected Debian/Ubuntu based system"
            echo ""

            log_step "Updating package lists..."
            $SUDO apt-get update -qq

            log_step "Installing build tools..."
            $SUDO apt-get install -y git curl wget build-essential lsb-release gnupg

            log_step "Installing Node.js 20+..."
            if ! check_command node; then
                curl -fsSL https://deb.nodesource.com/setup_20.x | $SUDO -E bash -
                $SUDO apt-get install -y nodejs
            else
                log_info "Node.js already installed: $(node --version)"
            fi

            log_step "Installing MongoDB..."
            if ! check_command mongod; then
                UBUNTU_CODENAME=$(lsb_release -cs)
                case "$UBUNTU_CODENAME" in
                    noble|jammy|focal)
                        MONGO_CODENAME="$UBUNTU_CODENAME"
                        ;;
                    *)
                        MONGO_CODENAME="jammy"
                        ;;
                esac

                curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | \
                    $SUDO gpg --dearmor -o /usr/share/keyrings/mongodb-server-8.0.gpg 2>/dev/null || true

                echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu ${MONGO_CODENAME}/mongodb-org/8.0 multiverse" | \
                    $SUDO tee /etc/apt/sources.list.d/mongodb-org-8.0.list > /dev/null

                $SUDO apt-get update -qq
                $SUDO apt-get install -y mongodb-org

                $SUDO systemctl start mongod
                $SUDO systemctl enable mongod
            else
                log_info "MongoDB already installed"
            fi
            ;;

        centos|rhel|fedora|rocky|almalinux)
            log_step "Detected RHEL/CentOS based system"
            echo ""

            if check_command dnf; then
                PKG_MGR="dnf"
            else
                PKG_MGR="yum"
            fi

            log_step "Installing build tools..."
            $SUDO $PKG_MGR groupinstall -y "Development Tools"
            $SUDO $PKG_MGR install -y git curl wget

            log_step "Installing Node.js 20+..."
            if ! check_command node; then
                curl -fsSL https://rpm.nodesource.com/setup_20.x | $SUDO bash -
                $SUDO $PKG_MGR install -y nodejs
            else
                log_info "Node.js already installed: $(node --version)"
            fi

            log_step "Installing MongoDB..."
            if ! check_command mongod; then
                cat <<EOF | $SUDO tee /etc/yum.repos.d/mongodb-org-8.0.repo
[mongodb-org-8.0]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/\$releasever/mongodb-org/8.0/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-8.0.asc
EOF
                $SUDO $PKG_MGR install -y mongodb-org
                $SUDO systemctl start mongod
                $SUDO systemctl enable mongod
            else
                log_info "MongoDB already installed"
            fi
            ;;

        *)
            log_warn "Unknown distribution: $OS_ID"
            log_warn "Please install manually: Node.js 20+, MongoDB 8.0+"
            ;;
    esac

    echo ""
    log_step "Verifying installations..."
    echo ""

    # Verify Node.js
    if check_command node; then
        NODE_VER=$(node --version 2>&1)
        echo -e "  Node.js:  ${GREEN}OK${NC} $NODE_VER"
    else
        echo -e "  Node.js:  ${RED}MISSING${NC}"
    fi

    # Verify npm
    if check_command npm; then
        NPM_VER=$(npm --version 2>&1)
        echo -e "  npm:      ${GREEN}OK${NC} v$NPM_VER"
    else
        echo -e "  npm:      ${RED}MISSING${NC}"
    fi

    # Verify MongoDB
    if check_command mongod || check_command mongosh; then
        echo -e "  MongoDB:  ${GREEN}OK${NC} Installed"
        if systemctl is-active --quiet mongod 2>/dev/null; then
            echo -e "            ${GREEN}OK${NC} Running"
        else
            echo -e "            ${YELLOW}!${NC} Not running (start with: sudo systemctl start mongod)"
        fi
    else
        echo -e "  MongoDB:  ${RED}MISSING${NC}"
    fi

    echo ""
    echo -e "${GREEN}System dependencies installed!${NC}"
    echo ""
}

# ============================================================
# Install Command
# ============================================================

do_install() {
    # Parse flags
    local install_mode="standard"
    for arg in "$@"; do
        case "$arg" in
            --user|--no-sudo) install_mode="user" ;;
            --conda)          install_mode="conda" ;;
        esac
    done

    echo -e "${CYAN}"
    echo "=============================================="
    case "$install_mode" in
        user)  echo "  CryoProcess - Installation (non-root)" ;;
        conda) echo "  CryoProcess - Installation (conda)" ;;
        *)     echo "  CryoProcess - Installation" ;;
    esac
    echo "=============================================="
    echo -e "${NC}"

    # Check system dependencies
    log_step "Checking system dependencies..."

    local missing_node=false
    local missing_mongo=false

    if ! check_command node; then
        missing_node=true
    else
        NODE_VER=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
        if [ "$NODE_VER" -lt 18 ]; then
            missing_node=true
        fi
    fi

    if ! check_command npm; then
        missing_node=true
    fi

    if ! check_command mongod && ! check_command mongosh; then
        missing_mongo=true
    fi

    if $missing_node || $missing_mongo; then
        echo ""
        log_warn "Missing system dependencies:"
        $missing_node && log_warn "  - Node.js 18+ / npm"
        $missing_mongo && log_warn "  - MongoDB"
        echo ""

        case "$install_mode" in
            user)
                # Non-root mode: download binaries locally (no sudo needed)
                log_info "Downloading dependencies locally (no sudo required)..."
                echo ""
                _install_user_deps
                ;;
            conda)
                # Conda mode: install into conda environment
                _install_conda_deps
                ;;
            *)
                # Standard mode: offer to install with sudo
                read -p "  Install them now? (requires sudo) [Y/n]: " answer
                answer=${answer:-Y}
                if [[ "$answer" =~ ^[Yy] ]]; then
                    echo ""
                    _install_system_deps
                    echo ""
                    log_step "Continuing with application setup..."
                    echo ""
                else
                    echo ""
                    log_info "Skipped. Install Node.js 20+ and MongoDB 8.0 manually, then run:"
                    echo "    ./cryoprocess.sh install"
                    echo ""
                    exit 1
                fi
                ;;
        esac
    else
        log_info "Node.js: $(node --version)"
        if check_command mongod; then
            log_info "MongoDB: installed"
        elif check_command mongosh; then
            log_info "MongoDB: installed (mongosh found)"
        fi
    fi

    # Verify node and npm are available before proceeding
    echo ""
    log_step "Verifying dependencies are available..."

    if ! check_command node; then
        log_error "Node.js is still not available after installation."
        log_error "Please install Node.js 20+ manually and try again."
        exit 1
    fi
    log_info "  node:  $(node --version)"

    if ! check_command npm; then
        log_error "npm is still not available after installation."
        log_error "Please install npm manually and try again."
        exit 1
    fi
    log_info "  npm:   v$(npm --version)"

    if check_command mongod; then
        log_info "  mongod: available"
    elif check_command mongosh; then
        log_info "  mongosh: available"
    else
        log_warn "  MongoDB not in PATH (will use MONGODB_URI from .env)"
    fi

    echo ""

    # ---- Step 1: Generate .env (prompt first, before long npm steps) ----
    log_step "[1/5] Configuring environment..."

    ENV_FILE="$SCRIPT_DIR/.env"

    if [ ! -f "$ENV_FILE" ]; then
        write_env_file
    else
        log_info ".env already exists (run './cryoprocess.sh reconfigure' to regenerate)"
    fi

    # Remove legacy backend/.env if it exists (consolidated to root)
    if [ -f "$BACKEND_DIR/.env" ]; then
        log_info "Removing legacy backend/.env (settings now in root .env)"
        rm -f "$BACKEND_DIR/.env"
    fi

    # Verify .env was created
    if [ ! -f "$SCRIPT_DIR/.env" ]; then
        log_error ".env file was not created. Installation cannot continue."
        exit 1
    fi
    log_info ".env file ready"

    echo ""

    # ---- Step 2: Backend dependencies ----
    log_step "[2/5] Installing backend dependencies..."
    cd "$BACKEND_DIR"
    if npm install --silent 2>/dev/null || npm install; then
        log_info "Backend dependencies installed"
    else
        log_error "Failed to install backend dependencies"
        exit 1
    fi
    cd "$SCRIPT_DIR"

    echo ""

    # ---- Step 3: Frontend dependencies ----
    log_step "[3/5] Installing frontend dependencies..."
    cd "$FRONTEND_DIR"
    if npm install --silent 2>/dev/null || npm install; then
        log_info "Frontend dependencies installed"
    else
        log_error "Failed to install frontend dependencies"
        exit 1
    fi
    cd "$SCRIPT_DIR"

    echo ""

    # ---- Step 4: Build frontend ----
    log_step "[4/5] Building frontend for production..."
    cd "$FRONTEND_DIR"
    if npm run build 2>&1; then
        log_info "Frontend build complete"
    else
        log_error "Frontend build failed. Check errors above."
        exit 1
    fi
    cd "$SCRIPT_DIR"

    # Copy build to backend
    rm -rf "$BACKEND_DIR/static"
    if [ -d "$FRONTEND_DIR/build" ]; then
        cp -r "$FRONTEND_DIR/build" "$BACKEND_DIR/static"
        log_info "Frontend deployed to backend/static"
    else
        log_error "Frontend build directory not found: $FRONTEND_DIR/build"
        exit 1
    fi

    echo ""

    # ---- Step 5: Create admin user ----
    log_step "[5/5] Setting up database and admin user..."

    # Check if MongoDB is reachable before trying admin creation
    if timeout 15 node "$BACKEND_DIR/src/utils/createAdmin.js"; then
        log_info "Database setup complete"
    else
        log_warn "Could not create admin user."
        log_warn "Make sure MongoDB is running, then run:"
        echo "    node backend/src/utils/createAdmin.js"
    fi

    echo ""
    echo -e "${GREEN}"
    echo "=============================================="
    echo "  Installation Complete!"
    echo "=============================================="
    echo -e "${NC}"
    echo ""
    echo "  Default Admin Credentials:"
    echo "  --------------------------"
    echo "  Email:    admin@example.com"
    echo "  Password: admin123"
    echo ""
    echo "  ** Change password after first login! **"
    echo ""
    echo "=============================================="
    echo ""
    echo "Next step: ./cryoprocess.sh start"
    echo ""
}

# ============================================================
# Ensure local MongoDB is running (--user / --conda modes)
# ============================================================

_ensure_local_mongod() {
    local MONGO_DATA="$DEPS_DIR/mongodb/data"
    # Only applies when we have a local data dir (user/conda installs)
    if [ -d "$MONGO_DATA" ]; then
        if ! pgrep -x mongod > /dev/null 2>&1; then
            log_step "Starting local MongoDB..."
            local MONGO_LOG="$DEPS_DIR/mongodb/mongod.log"
            mongod \
                --dbpath "$MONGO_DATA" \
                --logpath "$MONGO_LOG" \
                --port 27017 \
                --fork 2>/dev/null || log_warn "Could not start local MongoDB"
        fi
    fi
}

# ============================================================
# Start Command
# ============================================================

do_start() {
    echo -e "${CYAN}"
    echo "=============================================="
    echo "  Starting CryoProcess"
    echo "=============================================="
    echo -e "${NC}"

    # Start local MongoDB if needed (--user / --conda modes)
    _ensure_local_mongod

    # Check if .env exists
    if [ ! -f "$SCRIPT_DIR/.env" ]; then
        log_error ".env not found!"
        log_error "Run: ./cryoprocess.sh install"
        exit 1
    fi

    # Check if already running
    if [ -f "$PID_FILE" ]; then
        PID=$(cat "$PID_FILE")
        if ps -p $PID > /dev/null 2>&1; then
            log_warn "CryoProcess is already running (PID: $PID)"
            echo ""
            echo "  URL: http://localhost:$PORT"
            echo ""
            echo "  Stop with: ./cryoprocess.sh stop"
            exit 0
        fi
    fi

    # Kill any existing processes on port
    fuser -k $PORT/tcp 2>/dev/null || true
    pkill -f "node src/server.js" 2>/dev/null || true
    sleep 1

    # Start Node.js server
    log_step "Starting server on port $PORT..."

    cd "$BACKEND_DIR"
    NODE_ENV=production nohup node src/server.js > "$LOG_FILE" 2>&1 &
    NODE_PID=$!
    echo $NODE_PID > "$PID_FILE"
    cd "$SCRIPT_DIR"

    # Wait for server to start
    for i in {1..15}; do
        if curl -s "http://localhost:$PORT/api/health" > /dev/null 2>&1; then
            break
        fi
        sleep 1
    done

    # Check if started
    if curl -s "http://localhost:$PORT/api/health" > /dev/null 2>&1; then
        echo ""
        echo -e "${GREEN}"
        echo "=============================================="
        echo "  CryoProcess is running!"
        echo "=============================================="
        echo -e "${NC}"
        echo ""
        echo "  URL:      http://localhost:$PORT"
        echo "  Login:    admin@example.com / admin123"
        echo ""
        echo "  Commands:"
        echo "    ./cryoprocess.sh status   - Check status"
        echo "    ./cryoprocess.sh logs     - View logs"
        echo "    ./cryoprocess.sh stop     - Stop server"
        echo ""
    else
        log_error "Failed to start. Check logs:"
        echo ""
        tail -20 "$LOG_FILE"
        exit 1
    fi
}

# ============================================================
# Stop Command
# ============================================================

do_stop() {
    log_info "Stopping CryoProcess..."

    if [ -f "$PID_FILE" ]; then
        PID=$(cat "$PID_FILE")
        if ps -p $PID > /dev/null 2>&1; then
            kill $PID 2>/dev/null || true
            sleep 2
            if ps -p $PID > /dev/null 2>&1; then
                kill -9 $PID 2>/dev/null || true
            fi
        fi
        rm -f "$PID_FILE"
    fi

    # Kill any remaining processes
    fuser -k $PORT/tcp 2>/dev/null || true
    pkill -f "node src/server.js" 2>/dev/null || true

    # Stop local MongoDB if running (--user / --conda modes)
    local MONGO_DATA="$DEPS_DIR/mongodb/data"
    if [ -d "$MONGO_DATA" ] && pgrep -x mongod > /dev/null 2>&1; then
        log_info "Stopping local MongoDB..."
        mongod --dbpath "$MONGO_DATA" --shutdown 2>/dev/null || pkill -x mongod 2>/dev/null || true
    fi

    log_info "CryoProcess stopped"
}

# ============================================================
# Status Command
# ============================================================

do_status() {
    echo ""
    echo "CryoProcess Status"
    echo "=========================="
    echo ""

    # Node.js server
    if [ -f "$PID_FILE" ]; then
        PID=$(cat "$PID_FILE")
        if ps -p $PID > /dev/null 2>&1; then
            echo -e "  Server:    ${GREEN}Running${NC} (PID: $PID)"
            echo -e "  URL:       http://localhost:$PORT"

            # Check health
            if curl -s "http://localhost:$PORT/api/health" > /dev/null 2>&1; then
                echo -e "  Health:    ${GREEN}OK${NC}"
            else
                echo -e "  Health:    ${YELLOW}Not responding${NC}"
            fi
        else
            echo -e "  Server:    ${RED}Stopped${NC} (stale PID file)"
        fi
    else
        if lsof -i :$PORT > /dev/null 2>&1; then
            echo -e "  Server:    ${YELLOW}Running${NC} (no PID file)"
        else
            echo -e "  Server:    ${RED}Stopped${NC}"
        fi
    fi

    # MongoDB
    if pgrep -x mongod > /dev/null 2>&1; then
        echo -e "  MongoDB:   ${GREEN}Running${NC}"
    elif systemctl is-active --quiet mongod 2>/dev/null; then
        echo -e "  MongoDB:   ${GREEN}Running${NC}"
    else
        echo -e "  MongoDB:   ${YELLOW}Not detected${NC}"
    fi

    echo ""
}

# ============================================================
# Logs Command
# ============================================================

do_logs() {
    if [ -f "$LOG_FILE" ]; then
        echo "Showing logs (Ctrl+C to exit)..."
        echo ""
        tail -f "$LOG_FILE"
    else
        log_error "No log file found at $LOG_FILE"
    fi
}

# ============================================================
# Build Command
# ============================================================

do_build() {
    log_step "Rebuilding frontend..."

    cd "$FRONTEND_DIR"
    npm run build
    cd "$SCRIPT_DIR"

    rm -rf "$BACKEND_DIR/static"
    cp -r "$FRONTEND_DIR/build" "$BACKEND_DIR/static"

    log_info "Frontend rebuilt and deployed"
}

# ============================================================
# Reconfigure Command
# ============================================================

do_reconfigure() {
    echo -e "${CYAN}"
    echo "=============================================="
    echo "  CryoProcess - Reconfigure"
    echo "=============================================="
    echo -e "${NC}"

    ENV_FILE="$SCRIPT_DIR/.env"

    # Try to read old values as defaults
    if [ -f "$ENV_FILE" ]; then
        log_info "Reading existing values from .env..."
        # Source safely — ignore errors from corrupted lines
        while IFS='=' read -r key value; do
            # Skip comments and empty lines
            [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
            # Strip leading/trailing whitespace
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | xargs)
            # Export as OLD_ prefixed variable
            export "OLD_$key=$value"
        done < "$ENV_FILE" 2>/dev/null

        # Back up old file
        BACKUP="$ENV_FILE.backup.$(date +%Y%m%d_%H%M%S)"
        cp "$ENV_FILE" "$BACKUP"
        log_info "Backed up old .env to $(basename "$BACKUP")"
    else
        log_warn "No existing .env found — creating fresh config"
    fi

    write_env_file

    log_info "Reconfiguration complete"
    echo ""
}

# ============================================================
# Service Command (systemd daemon)
# ============================================================

SERVICE_NAME="cryoprocess"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

do_service() {
    local action="${1:-help}"

    case "$action" in
        start|setup|install)
            do_service_install
            ;;
        stop)
            if [ ! -f "$SERVICE_FILE" ]; then
                log_error "Service not installed. Run: ./cryoprocess.sh service start"
                exit 1
            fi
            if sudo systemctl stop "$SERVICE_NAME"; then
                log_info "Service stopped"
            else
                log_error "Failed to stop service"
                exit 1
            fi
            ;;
        restart)
            if [ ! -f "$SERVICE_FILE" ]; then
                log_error "Service not installed. Run: ./cryoprocess.sh service start"
                exit 1
            fi
            if sudo systemctl restart "$SERVICE_NAME"; then
                log_info "Service restarted"
            else
                log_error "Failed to restart service"
                exit 1
            fi
            ;;
        status)
            if [ ! -f "$SERVICE_FILE" ]; then
                log_error "Service not installed. Run: ./cryoprocess.sh service start"
                exit 1
            fi
            # systemctl status returns non-zero when stopped — don't let set -e kill us
            sudo systemctl status "$SERVICE_NAME" --no-pager || true
            ;;
        logs|log)
            if [ ! -f "$SERVICE_FILE" ]; then
                log_error "Service not installed. Run: ./cryoprocess.sh service start"
                exit 1
            fi
            journalctl -u "$SERVICE_NAME" -f
            ;;
        uninstall|remove)
            do_service_uninstall
            ;;
        *)
            echo ""
            echo "Usage: ./cryoprocess.sh service <start|stop|restart|status|logs|uninstall>"
            echo ""
            echo "  start       Install + enable + start daemon (auto-start on boot)"
            echo "  stop        Stop daemon"
            echo "  restart     Restart daemon"
            echo "  status      Show daemon status"
            echo "  logs        View daemon logs (Ctrl+C to exit)"
            echo "  uninstall   Stop + disable + remove daemon"
            echo ""
            ;;
    esac
}

do_service_install() {
    echo -e "${CYAN}"
    echo "=============================================="
    echo "  CryoProcess - Install systemd Service"
    echo "=============================================="
    echo -e "${NC}"

    # Check prerequisites
    if [ ! -f "$SCRIPT_DIR/.env" ]; then
        log_error ".env not found! Run: ./cryoprocess.sh install"
        exit 1
    fi

    if ! check_command systemctl; then
        log_error "systemd not found. This command requires a systemd-based system."
        exit 1
    fi

    # Detect Node.js path
    local NODE_BIN
    NODE_BIN=$(which node 2>/dev/null || true)
    if [ -z "$NODE_BIN" ]; then
        log_error "Node.js not found in PATH"
        exit 1
    fi

    # Detect user
    local RUN_USER
    RUN_USER=$(whoami)

    log_step "Creating systemd service..."
    echo ""
    echo "  Service:   $SERVICE_NAME"
    echo "  User:      $RUN_USER"
    echo "  Node:      $NODE_BIN"
    echo "  WorkDir:   $BACKEND_DIR"
    echo "  EnvFile:   $SCRIPT_DIR/.env"
    echo ""

    # Stop manual mode if running
    if [ -f "$PID_FILE" ]; then
        PID=$(cat "$PID_FILE")
        if ps -p $PID > /dev/null 2>&1; then
            log_warn "Stopping manual-mode server first (PID: $PID)..."
            do_stop
        fi
    fi

    # Write unit file
    sudo tee "$SERVICE_FILE" > /dev/null << SERVICEEOF
[Unit]
Description=CryoProcess - Cryo-EM Processing Platform
After=network.target mongod.service
Wants=mongod.service

[Service]
Type=simple
User=$RUN_USER
WorkingDirectory=$BACKEND_DIR
EnvironmentFile=$SCRIPT_DIR/.env
ExecStart=$NODE_BIN src/server.js
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SERVICEEOF

    sudo systemctl daemon-reload
    sudo systemctl enable "$SERVICE_NAME"
    sudo systemctl start "$SERVICE_NAME"

    # Wait for health check
    sleep 3
    if curl -s "http://localhost:$PORT/api/health" > /dev/null 2>&1; then
        echo ""
        echo -e "${GREEN}"
        echo "=============================================="
        echo "  Service installed and running!"
        echo "=============================================="
        echo -e "${NC}"
    else
        echo ""
        log_warn "Service installed but health check failed. Check logs:"
        echo "  journalctl -u $SERVICE_NAME -n 20"
    fi

    echo ""
    echo "  Manage with:"
    echo "    sudo systemctl stop $SERVICE_NAME"
    echo "    sudo systemctl restart $SERVICE_NAME"
    echo "    sudo systemctl status $SERVICE_NAME"
    echo "    journalctl -u $SERVICE_NAME -f"
    echo ""
}

do_service_uninstall() {
    echo -e "${CYAN}"
    echo "=============================================="
    echo "  CryoProcess - Remove systemd Service"
    echo "=============================================="
    echo -e "${NC}"

    if [ ! -f "$SERVICE_FILE" ]; then
        log_warn "Service not installed ($SERVICE_FILE not found)"
        return
    fi

    log_step "Stopping and removing service..."

    sudo systemctl stop "$SERVICE_NAME" 2>/dev/null || true
    sudo systemctl disable "$SERVICE_NAME" 2>/dev/null || true
    sudo rm -f "$SERVICE_FILE"
    sudo systemctl daemon-reload

    echo ""
    log_info "Service removed"
    echo ""
    echo "  To run manually: ./cryoprocess.sh start"
    echo ""
}

# ============================================================
# Dev Command (development mode)
# ============================================================

do_dev() {
    echo -e "${CYAN}"
    echo "=============================================="
    echo "  Starting Development Mode"
    echo "=============================================="
    echo -e "${NC}"

    log_info "Starting backend with auto-reload..."
    cd "$BACKEND_DIR"
    npm run dev
}

# ============================================================
# Uninstall Command
# ============================================================

do_uninstall() {
    echo -e "${CYAN}"
    echo "=============================================="
    echo "  CryoProcess - Uninstall"
    echo "=============================================="
    echo -e "${NC}"

    echo "  This will remove:"
    echo "    - Stop running server and local MongoDB"
    echo "    - Remove systemd service (if installed)"
    echo "    - Remove node_modules (backend + frontend)"
    echo "    - Remove frontend build"
    echo "    - Remove local deps/ (Node.js/MongoDB binaries)"
    echo "    - Remove conda environment (if installed via --conda)"
    echo "    - Remove PID and log files"
    echo ""
    echo "  This will NOT remove:"
    echo "    - Your .env config file"
    echo "    - MongoDB data (your projects database)"
    echo "    - Your project source code"
    echo ""

    read -p "  Are you sure? [y/N]: " confirm
    if [[ ! "$confirm" =~ ^[Yy] ]]; then
        log_info "Cancelled"
        return
    fi

    echo ""

    # 1. Stop server
    log_step "[1/6] Stopping server..."
    if [ -f "$PID_FILE" ]; then
        PID=$(cat "$PID_FILE")
        if ps -p $PID > /dev/null 2>&1; then
            kill $PID 2>/dev/null || true
            sleep 2
            kill -9 $PID 2>/dev/null || true
        fi
        rm -f "$PID_FILE"
    fi
    fuser -k $PORT/tcp 2>/dev/null || true
    pkill -f "node src/server.js" 2>/dev/null || true
    log_info "Server stopped"

    # 2. Stop local MongoDB (--user / --conda modes)
    log_step "[2/6] Stopping local MongoDB..."
    local MONGO_DATA="$DEPS_DIR/mongodb/data"
    if [ -d "$MONGO_DATA" ] && pgrep -x mongod > /dev/null 2>&1; then
        mongod --dbpath "$MONGO_DATA" --shutdown 2>/dev/null || pkill -x mongod 2>/dev/null || true
        log_info "Local MongoDB stopped"
    else
        log_info "No local MongoDB running"
    fi

    # 3. Remove systemd service
    log_step "[3/6] Removing systemd service..."
    if [ -f "$SERVICE_FILE" ]; then
        sudo systemctl stop "$SERVICE_NAME" 2>/dev/null || true
        sudo systemctl disable "$SERVICE_NAME" 2>/dev/null || true
        sudo rm -f "$SERVICE_FILE" 2>/dev/null || true
        sudo systemctl daemon-reload 2>/dev/null || true
        log_info "Service removed"
    else
        log_info "No systemd service installed"
    fi

    # 4. Remove node_modules and build artifacts
    log_step "[4/6] Removing node_modules and build artifacts..."
    rm -rf "$BACKEND_DIR/node_modules"
    rm -rf "$FRONTEND_DIR/node_modules"
    rm -rf "$FRONTEND_DIR/build"
    rm -rf "$BACKEND_DIR/static"
    log_info "node_modules and build artifacts removed"

    # 5. Remove local deps (--user mode binaries)
    log_step "[5/6] Removing local dependencies..."
    if [ -d "$DEPS_DIR" ]; then
        rm -rf "$DEPS_DIR"
        log_info "deps/ removed (Node.js/MongoDB binaries)"
    else
        log_info "No local deps/ directory"
    fi

    # 6. Remove conda environment (--conda mode)
    log_step "[6/6] Removing conda environment..."
    if [ -f "$CONDA_ENV_FILE" ]; then
        CRYO_CONDA_ENV=$(cat "$CONDA_ENV_FILE")
        if check_command conda; then
            eval "$(conda shell.bash hook 2>/dev/null)"
            conda deactivate 2>/dev/null || true
            conda env remove -n "$CRYO_CONDA_ENV" -y 2>/dev/null || true
            log_info "Conda environment '$CRYO_CONDA_ENV' removed"
        else
            log_warn "conda not found — remove environment manually: conda env remove -n $CRYO_CONDA_ENV"
        fi
        rm -f "$CONDA_ENV_FILE"
    else
        log_info "No conda environment"
    fi

    # Clean up PID and log files
    rm -rf "$PID_DIR" "$LOG_DIR"

    echo ""
    echo -e "${GREEN}"
    echo "=============================================="
    echo "  Uninstall Complete"
    echo "=============================================="
    echo -e "${NC}"
    echo ""
    echo "  Your .env config file is preserved."
    echo "  To reinstall: ./cryoprocess.sh install"
    echo ""
}

# ============================================================
# Database Backup Command
# ============================================================

do_backup() {
    echo -e "${CYAN}"
    echo "=============================================="
    echo "  CryoProcess - Database Backup"
    echo "=============================================="
    echo -e "${NC}"

    # Read MongoDB URI from .env
    local MONGO_URI="mongodb://localhost:27017/cryoprocess-db"
    if [ -f "$SCRIPT_DIR/.env" ]; then
        local env_uri
        env_uri=$(grep -E '^MONGODB_URI=' "$SCRIPT_DIR/.env" 2>/dev/null | cut -d'=' -f2-)
        if [ -n "$env_uri" ]; then
            MONGO_URI="$env_uri"
        fi
    fi

    # Extract database name from URI
    local DB_NAME
    DB_NAME=$(echo "$MONGO_URI" | sed 's|.*/||' | cut -d'?' -f1)
    DB_NAME="${DB_NAME:-cryoprocess-db}"

    # Check mongodump is available
    if ! check_command mongodump; then
        log_error "mongodump not found!"
        echo ""
        echo "  Install MongoDB Database Tools:"
        echo "    https://www.mongodb.com/try/download/database-tools"
        echo ""
        echo "  Or use mongosh to export manually:"
        echo "    mongosh \"$MONGO_URI\" --eval 'db.getCollectionNames()'"
        echo ""
        exit 1
    fi

    # Create backup directory
    local BACKUP_DIR="$SCRIPT_DIR/backups"
    mkdir -p "$BACKUP_DIR"

    local TIMESTAMP
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    local BACKUP_PATH="$BACKUP_DIR/${DB_NAME}_${TIMESTAMP}"

    log_step "Backing up database: $DB_NAME"
    echo "  URI:    $MONGO_URI"
    echo "  Output: $BACKUP_PATH/"
    echo ""

    if mongodump --uri="$MONGO_URI" --out="$BACKUP_PATH" 2>&1; then
        # Compress the backup
        log_step "Compressing backup..."
        local ARCHIVE="$BACKUP_PATH.tar.gz"
        tar -czf "$ARCHIVE" -C "$BACKUP_DIR" "$(basename "$BACKUP_PATH")"
        rm -rf "$BACKUP_PATH"

        echo ""
        echo -e "${GREEN}"
        echo "=============================================="
        echo "  Backup Complete"
        echo "=============================================="
        echo -e "${NC}"
        echo ""
        echo "  File: $ARCHIVE"
        echo "  Size: $(du -h "$ARCHIVE" | cut -f1)"
        echo ""
        echo "  Restore with:"
        echo "    tar -xzf $ARCHIVE && mongorestore --uri=\"$MONGO_URI\" --drop $(basename "$BACKUP_PATH")/"
        echo ""
    else
        log_error "Backup failed. Check MongoDB connection."
        rm -rf "$BACKUP_PATH"
        exit 1
    fi
}

# ============================================================
# Help
# ============================================================

show_help() {
    echo ""
    echo -e "${CYAN}CryoProcess - Control Script${NC}"
    echo ""
    echo "Usage: ./cryoprocess.sh <command> [options]"
    echo ""
    echo "Commands:"
    echo "  install            Full setup (install packages, build frontend, generate .env)"
    echo "  install --user     Non-root setup (downloads Node.js/MongoDB binaries locally)"
    echo "  install --conda    Conda setup (installs Node.js/MongoDB into conda env)"
    echo "  reconfigure        Regenerate .env (backs up old, preserves values)"
    echo "  start              Start production server (port $PORT)"
    echo "  stop               Stop server"
    echo "  restart            Restart server"
    echo "  status             Show server status"
    echo "  logs               View server logs (Ctrl+C to exit)"
    echo "  build              Rebuild frontend"
    echo "  uninstall          Remove all installed components (deps, build, service)"
    echo "  backup             Backup MongoDB database (compressed archive)"
    echo "  service start      Install + start systemd daemon (auto-start on boot)"
    echo "  service stop       Stop daemon"
    echo "  service uninstall  Stop + disable + remove daemon"
    echo "  service restart    Restart daemon"
    echo "  service status     Show daemon status"
    echo "  service logs       View daemon logs"
    echo "  dev                Start in development mode (with auto-reload)"
    echo "  help               Show this help"
    echo ""
    echo "Quick Start (with sudo — daemon, auto-starts on boot):"
    echo "  1. sudo ./cryoprocess.sh install"
    echo "  2. ./cryoprocess.sh service start     # done — server is running"
    echo ""
    echo "Quick Start (with sudo — manual background):"
    echo "  1. sudo ./cryoprocess.sh install"
    echo "  2. ./cryoprocess.sh start              # done — server is running"
    echo ""
    echo "Quick Start (non-root — downloads binaries locally, no sudo):"
    echo "  1. ./cryoprocess.sh install --user"
    echo "  2. ./cryoprocess.sh start"
    echo ""
    echo "Quick Start (conda — requires conda/mamba pre-installed):"
    echo "  1. ./cryoprocess.sh install --conda"
    echo "  2. ./cryoprocess.sh start"
    echo ""
    echo "Development:"
    echo "  ./cryoprocess.sh dev            # Backend with auto-reload"
    echo "  cd frontend && npm start        # Frontend dev server"
    echo ""
}

# ============================================================
# Main
# ============================================================

case "${1:-help}" in
    install|setup)
        shift
        do_install "$@"
        ;;
    reconfigure|reconfig)
        do_reconfigure
        ;;
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart)
        do_stop
        sleep 2
        do_start
        ;;
    status)
        do_status
        ;;
    logs|log)
        do_logs
        ;;
    build)
        do_build
        ;;
    uninstall)
        do_uninstall
        ;;
    backup)
        do_backup
        ;;
    service)
        do_service "$2"
        ;;
    dev|development)
        do_dev
        ;;
    help|--help|-h|"")
        show_help
        ;;
    *)
        log_error "Unknown command: $1"
        show_help
        exit 1
        ;;
esac
